name: Publish package to GitHub Packages
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      # Setup .npmrc file to publish to GitHub Packages
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
          cache-dependency-path: client/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: client
      - run: yarn build
        working-directory: client
      - run: yarn publish --new-version ${{ steps.version.outputs.version }}
        working-directory: client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"
          cache-dependency-path: client/yarn.lock
      - run: yarn build
        working-directory: client
      - run: yarn publish --new-version ${{ steps.version.outputs.version }}
        working-directory: client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
