name: Publish package to GitHub Packages
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - run: yarn install --frozen-lockfile 
        working-directory: client
      - run: yarn build
        working-directory: client
      - run: yarn publish
        working-directory: client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
